
###########################################
# Parameter Domain - BranchPred           #
###########################################

start_delimiter: "  -- <MicroArch>"
stop_delimiter: "  -- </MicroArch>"