/*
 * Copyright(C) ${YEAR} by Jonathan Saussereau. All rights reserved.
 *
 * All source codes and documentation contain proprietary confidential
 * information and are distributed under license. It may be used, copied
 * and/or disclosed only pursuant to the terms of a valid license agreement
 * with Jonathan Saussereau. This copyright must be retained at all times.
 *
 * autogenerated_lib.h
 * 
 * WARNING: This file was auto-generated (2023/01/05, 16:04:19).
 *
 * Manual changes to this file may cause unexpected behavior in your application.
 * Manual changes to this file will be overwritten if the code is regenerated.
 *
 */

#ifndef _AUTOGENERATED_LIB_H_
#define _AUTOGENERATED_LIB_H_


/*************************
  Registers Definition   
*************************/

#define READ_MASK                                  0b0000                          
#define WRITE_MASK_BYTE0                           0b0001                          
#define WRITE_MASK_BYTE1                           0b0010                          
#define WRITE_MASK_BYTE2                           0b0100                          
#define WRITE_MASK_BYTE3                           0b1000                          
#define WRITE_MASK_ALL                             0b1111                          
#define SPI_FLASH_ADDR                             0x00000000                      
#define SPI_FLASH_ADDR_MASK                        0xfe000000                      
#define SPI_FLASH_CONTROL_OFFSET                   0x01ffffff                      
#define IOF_ADDR                                   0x03000000                      
#define IOF_ADDR_MASK                              0xfffff000                      
#define IOF_SEL_OFFSET                             0x0                             
#define GPIO_ADDR                                  0x04000000                      
#define GPIO_ADDR_MASK                             0xfffff000                      
#define GPIO_WRITE_VALUE_OFFSET                    0x00                            
#define GPIO_READ_VALUE_OFFSET                     0x04                            
#define GPIO_OUTPUT_EN_OFFSET                      0x08                            
#define GPIO_PULLUP_EN_OFFSET                      0x0C                            
#define GPIO_PULLDOWN_EN_OFFSET                    0x10                            
#define PWM0_ADDR                                  0x05000000                      
#define PWM0_ADDR_MASK                             0xfffff000                      
#define PWM_CONFIG_OFFSET                          0x00                            
#define PWM_COUNTER_OFFSET                         0x08                            
#define PWM_SCALED_COUNTER_OFFSET                  0x10                            
#define PWM_COMPARE0_OFFSET                        0x20                            
#define PWM_COMPARE1_OFFSET                        0x24                            
#define PWM_COMPARE2_OFFSET                        0x28                            
#define PWM_COMPARE3_OFFSET                        0x2C                            
#define UART0_ADDR                                 0x09000000                      
#define UART0_ADDR_MASK                            0xfffff000                      
#define UART_DATA_TX_OFFSET                        0x00                            
#define UART_DATA_RX_OFFSET                        0x04                            
#define UART_CONFIG_OFFSET                         0x08                            
#define UART_STATUS_OFFSET                         0x0C                            
#define I2C_MASTER0_ADDR                           0x06000000                      
#define I2C_MASTER0_ADDR_MASK                      0xfffff000                      
#define I2C_DATA_TX_OFFSET                         0x00                            
#define I2C_DATA_RX_OFFSET                         0x04                            
#define I2C_CONFIG_OFFSET                          0x08                            
#define I2C_COMMAND_OFFSET                         0x12                            
#define I2C_STATUS_OFFSET                          0x16                            
#define SPI_SLAVE0_ADDR                            0x0b000000                      
#define SPI_SLAVE0_ADDR_MASK                       0xfffff000                      
#define SPI_CONFIG_OFFSET                          0x00                            
#define SPI_CMP_PATTERN_OFFSET                     0x04                            
#define SPI_CMP_PATTERN_MSK_OFFSET                 0x08                            
#define SPI_START_PATTERN_OFFSET                   0x0C                            
#define SPI_START_PATTERN_MSK_OFFSET               0x10                            
#define SPI_STATUS_OFFSET                          0x14                            
#define SPI_DATA_TX_OFFSET                         0x18                            
#define SPI_DATA_RX_OFFSET                         0x1C                            
#define SPI_MASTER0_ADDR                           0x07000000                      
#define SPI_MASTER0_ADDR_MASK                      0xfffff000                      
#define SPI_MASTER_CONFIG_OFFSET                   0x00                            
#define TIMER0_ADDR                                0x08000000                      
#define TIMER0_ADDR_MASK                           0xfffff000                      
#define TIMER_CONFIG_OFFSET                        0x00                            
#define TIMER_COUNTER_MSB_OFFSET                   0x08                            
#define TIMER_COUNTER_LSB_OFFSET                   0x10                            
#define TIMER_SCALED_COUNTER_OFFSET                0x12                            
#define TIMER_COMPARE_OFFSET                       0x20                            
#define DEBUG_ADDR                                 0x0A000000                      
#define DEBUG_ADDR_MASK                            0xfffff000                      
#define DEBUG_REG0_OFFSET                          0x00                            
#define DEBUG_REG1_OFFSET                          0x04                            
#define DEBUG_REG2_OFFSET                          0x08                            
#define DEBUG_REG3_OFFSET                          0x0c                            
#define DEBUG_REG4_OFFSET                          0x10                            
#define DEBUG_REG5_OFFSET                          0x14                            
#define DEBUG_REG6_OFFSET                          0x18                            
#define DEBUG_REG7_OFFSET                          0x1c                            
#define DEBUG_REG8_OFFSET                          0x20                            
#define DMEM_ADDR                                  0x10000000                      
#define DMEM_ADDR_MASK                             0xff000000                      
#define DMEM2_ADDR                                 0x20000000                      
#define DMEM2_ADDR_MASK                            0xfffff000                      
#define IMEM_ADDR                                  0xf0000000                      
#define IMEM_ADDR_MASK                             0xf0000000                      
#define SPI_SLAVE1_ADDR                            0xffffffff                      
#define SPI_SLAVE1_ADDR_MASK                       0x00000fff                      
#define SPI_SLAVE_CONGIG_OFFSET                    0x00                            
#define SPI_SLAVE_CONGIG_OFFSET0                   0x00                            
#define SPI_SLAVE_CONGIG_OFFSET1                   0x01                            
#define SPI_SLAVE_CONGIG_OFFSET2                   0x02                            
#define SPI_SLAVE_CONGIG_OFFSET3                   0x03                            
#define SPI_SLAVE_SOC_CTRL_OFFSET                  0x04                            
#define SPI_SLAVE_SOC_CTRL_OFFSET0                 0x04                            
#define SPI_SLAVE_SOC_CTRL_OFFSET1                 0x05                            
#define SPI_SLAVE_SOC_CTRL_OFFSET2                 0x06                            
#define SPI_SLAVE_SOC_CTRL_OFFSET3                 0x07                            



/*************************
   Bitfields Definition   
*************************/


//qspi_flash_registers:

typedef union {
  struct {
    unsigned long bb_flash_in                    : 4;
    unsigned long bb_flash_out                   : 4;
    unsigned long bb_flash_clk                   : 1;
    unsigned long bb_flash_csb                   : 1;
    unsigned long reserved0                      : 2;
    unsigned long bb_flash_oe                    : 4;
    unsigned long reserved1                      : 4;
    unsigned long dummy                          : 4;
    unsigned long continuous_read                : 1;
    unsigned long access_mode                    : 2;
    unsigned long reserved2                      : 4;
    unsigned long enable                         : 1;
  };
} qspi_flash_control_t;

#define _QSPI_FLASH_CONTROL_BB_FLASH_IN_POSN       0x0
#define _QSPI_FLASH_CONTROL_BB_FLASH_IN_SIZE       0x4
#define _QSPI_FLASH_CONTROL_BB_FLASH_IN_MASK       0x0000000f
#define _QSPI_FLASH_CONTROL_BB_FLASH_OUT_POSN      0x4
#define _QSPI_FLASH_CONTROL_BB_FLASH_OUT_SIZE      0x4
#define _QSPI_FLASH_CONTROL_BB_FLASH_OUT_MASK      0x000000f0
#define _QSPI_FLASH_CONTROL_BB_FLASH_CLK_POSN      0x8
#define _QSPI_FLASH_CONTROL_BB_FLASH_CLK_SIZE      0x1
#define _QSPI_FLASH_CONTROL_BB_FLASH_CLK_MASK      0x00000100
#define _QSPI_FLASH_CONTROL_BB_FLASH_CSB_POSN      0x9
#define _QSPI_FLASH_CONTROL_BB_FLASH_CSB_SIZE      0x1
#define _QSPI_FLASH_CONTROL_BB_FLASH_CSB_MASK      0x00000200
#define _QSPI_FLASH_CONTROL_RESERVED0_POSN         0xa
#define _QSPI_FLASH_CONTROL_RESERVED0_SIZE         0x2
#define _QSPI_FLASH_CONTROL_RESERVED0_MASK         0x00000c00
#define _QSPI_FLASH_CONTROL_BB_FLASH_OE_POSN       0xc
#define _QSPI_FLASH_CONTROL_BB_FLASH_OE_SIZE       0x4
#define _QSPI_FLASH_CONTROL_BB_FLASH_OE_MASK       0x0000f000
#define _QSPI_FLASH_CONTROL_RESERVED1_POSN         0x10
#define _QSPI_FLASH_CONTROL_RESERVED1_SIZE         0x4
#define _QSPI_FLASH_CONTROL_RESERVED1_MASK         0x000f0000
#define _QSPI_FLASH_CONTROL_DUMMY_POSN             0x14
#define _QSPI_FLASH_CONTROL_DUMMY_SIZE             0x4
#define _QSPI_FLASH_CONTROL_DUMMY_MASK             0x00f00000
#define _QSPI_FLASH_CONTROL_CONTINUOUS_READ_POSN   0x18
#define _QSPI_FLASH_CONTROL_CONTINUOUS_READ_SIZE   0x1
#define _QSPI_FLASH_CONTROL_CONTINUOUS_READ_MASK   0x01000000
#define _QSPI_FLASH_CONTROL_ACCESS_MODE_POSN       0x19
#define _QSPI_FLASH_CONTROL_ACCESS_MODE_SIZE       0x2
#define _QSPI_FLASH_CONTROL_ACCESS_MODE_MASK       0x06000000
#define _QSPI_FLASH_CONTROL_RESERVED2_POSN         0x1b
#define _QSPI_FLASH_CONTROL_RESERVED2_SIZE         0x4
#define _QSPI_FLASH_CONTROL_RESERVED2_MASK         0x78000000
#define _QSPI_FLASH_CONTROL_ENABLE_POSN            0x1f
#define _QSPI_FLASH_CONTROL_ENABLE_SIZE            0x1
#define _QSPI_FLASH_CONTROL_ENABLE_MASK            0x80000000


//access_mode_e:

#define SINGLE                                     0b00
#define DUAL                                       0b01
#define QUAD                                       0b10
#define QUAD_DDR                                   0b11


//iof_registers:

typedef union {
  struct {
    unsigned long sel                            : 24;
    unsigned long reserved                       : 8;
  };
} iof_config_t;

#define _IOF_CONFIG_SEL_POSN                       0x0
#define _IOF_CONFIG_SEL_SIZE                       0x18
#define _IOF_CONFIG_SEL_MASK                       0x00ffffff
#define _IOF_CONFIG_RESERVED_POSN                  0x18
#define _IOF_CONFIG_RESERVED_SIZE                  0x8
#define _IOF_CONFIG_RESERVED_MASK                  0xff000000



//gpio_registers:

typedef union {
  struct {
    unsigned long value                          : 24;
    unsigned long reserved                       : 8;
  };
} gpio_t;

#define _GPIO_VALUE_POSN                           0x0
#define _GPIO_VALUE_SIZE                           0x18
#define _GPIO_VALUE_MASK                           0x00ffffff
#define _GPIO_RESERVED_POSN                        0x18
#define _GPIO_RESERVED_SIZE                        0x8
#define _GPIO_RESERVED_MASK                        0xff000000



//pwm_registers:

typedef union {
  struct {
    unsigned long scale                          : 4;
    unsigned long reserved0                      : 4;
    unsigned long sticky                         : 1;
    unsigned long zero_cmp                       : 1;
    unsigned long deglitch                       : 1;
    unsigned long reserved1                      : 1;
    unsigned long en_always                      : 1;
    unsigned long en_oneshot                     : 1;
    unsigned long reserved2                      : 2;
    unsigned long compare0_center                : 1;
    unsigned long compare1_center                : 1;
    unsigned long compare2_center                : 1;
    unsigned long compare3_center                : 1;
    unsigned long compare0_complement            : 1;
    unsigned long compare1_complement            : 1;
    unsigned long compare2_complement            : 1;
    unsigned long compare3_complement            : 1;
    unsigned long compare0_gang                  : 1;
    unsigned long compare1_gang                  : 1;
    unsigned long compare2_gang                  : 1;
    unsigned long compare3_gang                  : 1;
    unsigned long compare0_ip                    : 1;
    unsigned long compare1_ip                    : 1;
    unsigned long compare2_ip                    : 1;
    unsigned long compare3_ip                    : 1;
  };
} pwm_config_t;

#define _PWM_CONFIG_SCALE_POSN                     0x0
#define _PWM_CONFIG_SCALE_SIZE                     0x4
#define _PWM_CONFIG_SCALE_MASK                     0x0000000f
#define _PWM_CONFIG_RESERVED0_POSN                 0x4
#define _PWM_CONFIG_RESERVED0_SIZE                 0x4
#define _PWM_CONFIG_RESERVED0_MASK                 0x000000f0
#define _PWM_CONFIG_STICKY_POSN                    0x8
#define _PWM_CONFIG_STICKY_SIZE                    0x1
#define _PWM_CONFIG_STICKY_MASK                    0x00000100
#define _PWM_CONFIG_ZERO_CMP_POSN                  0x9
#define _PWM_CONFIG_ZERO_CMP_SIZE                  0x1
#define _PWM_CONFIG_ZERO_CMP_MASK                  0x00000200
#define _PWM_CONFIG_DEGLITCH_POSN                  0xa
#define _PWM_CONFIG_DEGLITCH_SIZE                  0x1
#define _PWM_CONFIG_DEGLITCH_MASK                  0x00000400
#define _PWM_CONFIG_RESERVED1_POSN                 0xb
#define _PWM_CONFIG_RESERVED1_SIZE                 0x1
#define _PWM_CONFIG_RESERVED1_MASK                 0x00000800
#define _PWM_CONFIG_EN_ALWAYS_POSN                 0xc
#define _PWM_CONFIG_EN_ALWAYS_SIZE                 0x1
#define _PWM_CONFIG_EN_ALWAYS_MASK                 0x00001000
#define _PWM_CONFIG_EN_ONESHOT_POSN                0xd
#define _PWM_CONFIG_EN_ONESHOT_SIZE                0x1
#define _PWM_CONFIG_EN_ONESHOT_MASK                0x00002000
#define _PWM_CONFIG_RESERVED2_POSN                 0xe
#define _PWM_CONFIG_RESERVED2_SIZE                 0x2
#define _PWM_CONFIG_RESERVED2_MASK                 0x0000c000
#define _PWM_CONFIG_COMPARE0_CENTER_POSN           0x10
#define _PWM_CONFIG_COMPARE0_CENTER_SIZE           0x1
#define _PWM_CONFIG_COMPARE0_CENTER_MASK           0x00010000
#define _PWM_CONFIG_COMPARE1_CENTER_POSN           0x11
#define _PWM_CONFIG_COMPARE1_CENTER_SIZE           0x1
#define _PWM_CONFIG_COMPARE1_CENTER_MASK           0x00020000
#define _PWM_CONFIG_COMPARE2_CENTER_POSN           0x12
#define _PWM_CONFIG_COMPARE2_CENTER_SIZE           0x1
#define _PWM_CONFIG_COMPARE2_CENTER_MASK           0x00040000
#define _PWM_CONFIG_COMPARE3_CENTER_POSN           0x13
#define _PWM_CONFIG_COMPARE3_CENTER_SIZE           0x1
#define _PWM_CONFIG_COMPARE3_CENTER_MASK           0x00080000
#define _PWM_CONFIG_COMPARE0_COMPLEMENT_POSN       0x14
#define _PWM_CONFIG_COMPARE0_COMPLEMENT_SIZE       0x1
#define _PWM_CONFIG_COMPARE0_COMPLEMENT_MASK       0x00100000
#define _PWM_CONFIG_COMPARE1_COMPLEMENT_POSN       0x15
#define _PWM_CONFIG_COMPARE1_COMPLEMENT_SIZE       0x1
#define _PWM_CONFIG_COMPARE1_COMPLEMENT_MASK       0x00200000
#define _PWM_CONFIG_COMPARE2_COMPLEMENT_POSN       0x16
#define _PWM_CONFIG_COMPARE2_COMPLEMENT_SIZE       0x1
#define _PWM_CONFIG_COMPARE2_COMPLEMENT_MASK       0x00400000
#define _PWM_CONFIG_COMPARE3_COMPLEMENT_POSN       0x17
#define _PWM_CONFIG_COMPARE3_COMPLEMENT_SIZE       0x1
#define _PWM_CONFIG_COMPARE3_COMPLEMENT_MASK       0x00800000
#define _PWM_CONFIG_COMPARE0_GANG_POSN             0x18
#define _PWM_CONFIG_COMPARE0_GANG_SIZE             0x1
#define _PWM_CONFIG_COMPARE0_GANG_MASK             0x01000000
#define _PWM_CONFIG_COMPARE1_GANG_POSN             0x19
#define _PWM_CONFIG_COMPARE1_GANG_SIZE             0x1
#define _PWM_CONFIG_COMPARE1_GANG_MASK             0x02000000
#define _PWM_CONFIG_COMPARE2_GANG_POSN             0x1a
#define _PWM_CONFIG_COMPARE2_GANG_SIZE             0x1
#define _PWM_CONFIG_COMPARE2_GANG_MASK             0x04000000
#define _PWM_CONFIG_COMPARE3_GANG_POSN             0x1b
#define _PWM_CONFIG_COMPARE3_GANG_SIZE             0x1
#define _PWM_CONFIG_COMPARE3_GANG_MASK             0x08000000
#define _PWM_CONFIG_COMPARE0_IP_POSN               0x1c
#define _PWM_CONFIG_COMPARE0_IP_SIZE               0x1
#define _PWM_CONFIG_COMPARE0_IP_MASK               0x10000000
#define _PWM_CONFIG_COMPARE1_IP_POSN               0x1d
#define _PWM_CONFIG_COMPARE1_IP_SIZE               0x1
#define _PWM_CONFIG_COMPARE1_IP_MASK               0x20000000
#define _PWM_CONFIG_COMPARE2_IP_POSN               0x1e
#define _PWM_CONFIG_COMPARE2_IP_SIZE               0x1
#define _PWM_CONFIG_COMPARE2_IP_MASK               0x40000000
#define _PWM_CONFIG_COMPARE3_IP_POSN               0x1f
#define _PWM_CONFIG_COMPARE3_IP_SIZE               0x1
#define _PWM_CONFIG_COMPARE3_IP_MASK               0x80000000


typedef union {
  struct {
    unsigned long value                          : 31;
    unsigned long reserved                       : 1;
  };
} pwm_counter_t;

#define _PWM_COUNTER_VALUE_POSN                    0x0
#define _PWM_COUNTER_VALUE_SIZE                    0x1f
#define _PWM_COUNTER_VALUE_MASK                    0x7fffffff
#define _PWM_COUNTER_RESERVED_POSN                 0x1f
#define _PWM_COUNTER_RESERVED_SIZE                 0x1
#define _PWM_COUNTER_RESERVED_MASK                 0x80000000


typedef union {
  struct {
    unsigned long value                          : 16;
    unsigned long reserved                       : 16;
  };
} pwm_scounter_t;

#define _PWM_SCOUNTER_VALUE_POSN                   0x0
#define _PWM_SCOUNTER_VALUE_SIZE                   0x10
#define _PWM_SCOUNTER_VALUE_MASK                   0x0000ffff
#define _PWM_SCOUNTER_RESERVED_POSN                0x10
#define _PWM_SCOUNTER_RESERVED_SIZE                0x10
#define _PWM_SCOUNTER_RESERVED_MASK                0xffff0000



//i2c_registers:

typedef union {
  struct {
    unsigned long prescale                       : 16;
    unsigned long reserved0                      : 6;
    unsigned long interrupt_enable               : 1;
    unsigned long system_enable                  : 1;
    unsigned long reserved1                      : 8;
  };
} i2c_config_t;

#define _I2C_CONFIG_PRESCALE_POSN                  0x0
#define _I2C_CONFIG_PRESCALE_SIZE                  0x10
#define _I2C_CONFIG_PRESCALE_MASK                  0x0000ffff
#define _I2C_CONFIG_RESERVED0_POSN                 0x10
#define _I2C_CONFIG_RESERVED0_SIZE                 0x6
#define _I2C_CONFIG_RESERVED0_MASK                 0x003f0000
#define _I2C_CONFIG_INTERRUPT_ENABLE_POSN          0x16
#define _I2C_CONFIG_INTERRUPT_ENABLE_SIZE          0x1
#define _I2C_CONFIG_INTERRUPT_ENABLE_MASK          0x00400000
#define _I2C_CONFIG_SYSTEM_ENABLE_POSN             0x17
#define _I2C_CONFIG_SYSTEM_ENABLE_SIZE             0x1
#define _I2C_CONFIG_SYSTEM_ENABLE_MASK             0x00800000
#define _I2C_CONFIG_RESERVED1_POSN                 0x18
#define _I2C_CONFIG_RESERVED1_SIZE                 0x8
#define _I2C_CONFIG_RESERVED1_MASK                 0xff000000


typedef union {
  struct {
    unsigned long interrupt_acknowledge          : 1;
    unsigned long reserved0                      : 2;
    unsigned long acknowledge                    : 1;
    unsigned long write                          : 1;
    unsigned long read                           : 1;
    unsigned long stop                           : 1;
    unsigned long start                          : 1;
    unsigned long reserved1                      : 24;
  };
} i2c_command_t;

#define _I2C_COMMAND_INTERRUPT_ACKNOWLEDGE_POSN    0x0
#define _I2C_COMMAND_INTERRUPT_ACKNOWLEDGE_SIZE    0x1
#define _I2C_COMMAND_INTERRUPT_ACKNOWLEDGE_MASK    0x00000001
#define _I2C_COMMAND_RESERVED0_POSN                0x1
#define _I2C_COMMAND_RESERVED0_SIZE                0x2
#define _I2C_COMMAND_RESERVED0_MASK                0x00000006
#define _I2C_COMMAND_ACKNOWLEDGE_POSN              0x3
#define _I2C_COMMAND_ACKNOWLEDGE_SIZE              0x1
#define _I2C_COMMAND_ACKNOWLEDGE_MASK              0x00000008
#define _I2C_COMMAND_WRITE_POSN                    0x4
#define _I2C_COMMAND_WRITE_SIZE                    0x1
#define _I2C_COMMAND_WRITE_MASK                    0x00000010
#define _I2C_COMMAND_READ_POSN                     0x5
#define _I2C_COMMAND_READ_SIZE                     0x1
#define _I2C_COMMAND_READ_MASK                     0x00000020
#define _I2C_COMMAND_STOP_POSN                     0x6
#define _I2C_COMMAND_STOP_SIZE                     0x1
#define _I2C_COMMAND_STOP_MASK                     0x00000040
#define _I2C_COMMAND_START_POSN                    0x7
#define _I2C_COMMAND_START_SIZE                    0x1
#define _I2C_COMMAND_START_MASK                    0x00000080
#define _I2C_COMMAND_RESERVED1_POSN                0x8
#define _I2C_COMMAND_RESERVED1_SIZE                0x18
#define _I2C_COMMAND_RESERVED1_MASK                0xffffff00


typedef union {
  struct {
    unsigned long interrupt_pending              : 1;
    unsigned long transfer_in_progress           : 1;
    unsigned long reserved0                      : 3;
    unsigned long arbitrary_lost                 : 1;
    unsigned long i2c_busy                       : 1;
    unsigned long receive_acknowledge            : 1;
    unsigned long reserved1                      : 24;
  };
} i2c_status_t;

#define _I2C_STATUS_INTERRUPT_PENDING_POSN         0x0
#define _I2C_STATUS_INTERRUPT_PENDING_SIZE         0x1
#define _I2C_STATUS_INTERRUPT_PENDING_MASK         0x00000001
#define _I2C_STATUS_TRANSFER_IN_PROGRESS_POSN      0x1
#define _I2C_STATUS_TRANSFER_IN_PROGRESS_SIZE      0x1
#define _I2C_STATUS_TRANSFER_IN_PROGRESS_MASK      0x00000002
#define _I2C_STATUS_RESERVED0_POSN                 0x2
#define _I2C_STATUS_RESERVED0_SIZE                 0x3
#define _I2C_STATUS_RESERVED0_MASK                 0x0000001c
#define _I2C_STATUS_ARBITRARY_LOST_POSN            0x5
#define _I2C_STATUS_ARBITRARY_LOST_SIZE            0x1
#define _I2C_STATUS_ARBITRARY_LOST_MASK            0x00000020
#define _I2C_STATUS_I2C_BUSY_POSN                  0x6
#define _I2C_STATUS_I2C_BUSY_SIZE                  0x1
#define _I2C_STATUS_I2C_BUSY_MASK                  0x00000040
#define _I2C_STATUS_RECEIVE_ACKNOWLEDGE_POSN       0x7
#define _I2C_STATUS_RECEIVE_ACKNOWLEDGE_SIZE       0x1
#define _I2C_STATUS_RECEIVE_ACKNOWLEDGE_MASK       0x00000080
#define _I2C_STATUS_RESERVED1_POSN                 0x8
#define _I2C_STATUS_RESERVED1_SIZE                 0x18
#define _I2C_STATUS_RESERVED1_MASK                 0xffffff00


typedef union {
  struct {
    unsigned long value                          : 8;
    unsigned long reserved                       : 24;
  };
} i2c_data_t;

#define _I2C_DATA_VALUE_POSN                       0x0
#define _I2C_DATA_VALUE_SIZE                       0x8
#define _I2C_DATA_VALUE_MASK                       0x000000ff
#define _I2C_DATA_RESERVED_POSN                    0x8
#define _I2C_DATA_RESERVED_SIZE                    0x18
#define _I2C_DATA_RESERVED_MASK                    0xffffff00



//spi_slave_registers:

typedef union {
  struct {
    unsigned long wait_for_msg_start             : 1;
    unsigned long no_current_msg                 : 1;
    unsigned long use_msg_size                   : 1;
    unsigned long msg_size_byte                  : 4;
    unsigned long msg_size_init_value            : 4;
    unsigned long write_start_pattern            : 1;
    unsigned long send_on_compare                : 1;
    unsigned long compare_offset                 : 4;
    unsigned long send_countdown                 : 7;
    unsigned long reserved1                      : 11;
  };
} spi_config_t;

#define _SPI_CONFIG_WAIT_FOR_MSG_START_POSN        0x0
#define _SPI_CONFIG_WAIT_FOR_MSG_START_SIZE        0x1
#define _SPI_CONFIG_WAIT_FOR_MSG_START_MASK        0x000000001
#define _SPI_CONFIG_NO_CURRENT_MSG_POSN            0x1
#define _SPI_CONFIG_NO_CURRENT_MSG_SIZE            0x1
#define _SPI_CONFIG_NO_CURRENT_MSG_MASK            0x000000002
#define _SPI_CONFIG_USE_MSG_SIZE_POSN              0x2
#define _SPI_CONFIG_USE_MSG_SIZE_SIZE              0x1
#define _SPI_CONFIG_USE_MSG_SIZE_MASK              0x000000004
#define _SPI_CONFIG_MSG_SIZE_BYTE_POSN             0x3
#define _SPI_CONFIG_MSG_SIZE_BYTE_SIZE             0x4
#define _SPI_CONFIG_MSG_SIZE_BYTE_MASK             0x000000078
#define _SPI_CONFIG_MSG_SIZE_INIT_VALUE_POSN       0x7
#define _SPI_CONFIG_MSG_SIZE_INIT_VALUE_SIZE       0x4
#define _SPI_CONFIG_MSG_SIZE_INIT_VALUE_MASK       0x000000780
#define _SPI_CONFIG_WRITE_START_PATTERN_POSN       0xb
#define _SPI_CONFIG_WRITE_START_PATTERN_SIZE       0x1
#define _SPI_CONFIG_WRITE_START_PATTERN_MASK       0x000000800
#define _SPI_CONFIG_SEND_ON_COMPARE_POSN           0xc
#define _SPI_CONFIG_SEND_ON_COMPARE_SIZE           0x1
#define _SPI_CONFIG_SEND_ON_COMPARE_MASK           0x000001000
#define _SPI_CONFIG_COMPARE_OFFSET_POSN            0xd
#define _SPI_CONFIG_COMPARE_OFFSET_SIZE            0x4
#define _SPI_CONFIG_COMPARE_OFFSET_MASK            0x00001e000
#define _SPI_CONFIG_SEND_COUNTDOWN_POSN            0x11
#define _SPI_CONFIG_SEND_COUNTDOWN_SIZE            0x7
#define _SPI_CONFIG_SEND_COUNTDOWN_MASK            0x000fe0000
#define _SPI_CONFIG_RESERVED1_POSN                 0x18
#define _SPI_CONFIG_RESERVED1_SIZE                 0xb
#define _SPI_CONFIG_RESERVED1_MASK                 0x7ff000000


typedef union {
  struct {
    unsigned long value                          : 32;
  };
} spi_cmp_pattern_t;

#define _SPI_CMP_PATTERN_VALUE_POSN                0x0
#define _SPI_CMP_PATTERN_VALUE_SIZE                0x20
#define _SPI_CMP_PATTERN_VALUE_MASK                0xffffffff


typedef union {
  struct {
    unsigned long value                          : 32;
  };
} spi_cmp_pattern_msk_t;

#define _SPI_CMP_PATTERN_MSK_VALUE_POSN            0x0
#define _SPI_CMP_PATTERN_MSK_VALUE_SIZE            0x20
#define _SPI_CMP_PATTERN_MSK_VALUE_MASK            0xffffffff


typedef union {
  struct {
    unsigned long value                          : 32;
  };
} spi_start_pattern_t;

#define _SPI_START_PATTERN_VALUE_POSN              0x0
#define _SPI_START_PATTERN_VALUE_SIZE              0x20
#define _SPI_START_PATTERN_VALUE_MASK              0xffffffff


typedef union {
  struct {
    unsigned long value                          : 32;
  };
} spi_start_pattern_msk_t;

#define _SPI_START_PATTERN_MSK_VALUE_POSN          0x0
#define _SPI_START_PATTERN_MSK_VALUE_SIZE          0x20
#define _SPI_START_PATTERN_MSK_VALUE_MASK          0xffffffff


typedef union {
  struct {
    unsigned long mosi_fifo_full                 : 1;
    unsigned long reserved0                      : 7;
    unsigned long mosi_fifo_empty                : 1;
    unsigned long reserved1                      : 7;
    unsigned long miso_fifo_full                 : 1;
    unsigned long reserved2                      : 7;
    unsigned long miso_fifo_empty                : 1;
    unsigned long reserved3                      : 7;
  };
} spi_status_t;

#define _SPI_STATUS_MOSI_FIFO_FULL_POSN            0x0
#define _SPI_STATUS_MOSI_FIFO_FULL_SIZE            0x1
#define _SPI_STATUS_MOSI_FIFO_FULL_MASK            0x00000001
#define _SPI_STATUS_RESERVED0_POSN                 0x1
#define _SPI_STATUS_RESERVED0_SIZE                 0x7
#define _SPI_STATUS_RESERVED0_MASK                 0x000000fe
#define _SPI_STATUS_MOSI_FIFO_EMPTY_POSN           0x8
#define _SPI_STATUS_MOSI_FIFO_EMPTY_SIZE           0x1
#define _SPI_STATUS_MOSI_FIFO_EMPTY_MASK           0x00000100
#define _SPI_STATUS_RESERVED1_POSN                 0x9
#define _SPI_STATUS_RESERVED1_SIZE                 0x7
#define _SPI_STATUS_RESERVED1_MASK                 0x0000fe00
#define _SPI_STATUS_MISO_FIFO_FULL_POSN            0x10
#define _SPI_STATUS_MISO_FIFO_FULL_SIZE            0x1
#define _SPI_STATUS_MISO_FIFO_FULL_MASK            0x00010000
#define _SPI_STATUS_RESERVED2_POSN                 0x11
#define _SPI_STATUS_RESERVED2_SIZE                 0x7
#define _SPI_STATUS_RESERVED2_MASK                 0x00fe0000
#define _SPI_STATUS_MISO_FIFO_EMPTY_POSN           0x18
#define _SPI_STATUS_MISO_FIFO_EMPTY_SIZE           0x1
#define _SPI_STATUS_MISO_FIFO_EMPTY_MASK           0x01000000
#define _SPI_STATUS_RESERVED3_POSN                 0x19
#define _SPI_STATUS_RESERVED3_SIZE                 0x7
#define _SPI_STATUS_RESERVED3_MASK                 0xfe000000


typedef union {
  struct {
    unsigned long value                          : 8;
    unsigned long reserved                       : 24;
  };
} spi_data_t;

#define _SPI_DATA_VALUE_POSN                       0x0
#define _SPI_DATA_VALUE_SIZE                       0x8
#define _SPI_DATA_VALUE_MASK                       0x000000ff
#define _SPI_DATA_RESERVED_POSN                    0x8
#define _SPI_DATA_RESERVED_SIZE                    0x18
#define _SPI_DATA_RESERVED_MASK                    0xffffff00



//timer_registers:

typedef union {
  struct {
    unsigned long postscale                      : 4;
    unsigned long reserved0                      : 4;
    unsigned long prescale                       : 8;
    unsigned long zero_cmp                       : 1;
    unsigned long count_up                       : 1;
    unsigned long en_oneshot                     : 1;
    unsigned long en_always                      : 1;
    unsigned long clock_source                   : 1;
    unsigned long sticky                         : 1;
    unsigned long compare_ie                     : 1;
    unsigned long overflow_ie                    : 1;
    unsigned long compare_if                     : 1;
    unsigned long overflow_if                    : 1;
    unsigned long compare_ip                     : 1;
    unsigned long overflow_ip                    : 1;
    unsigned long reserved1                      : 6;
  };
} timer_config_t;

#define _TIMER_CONFIG_POSTSCALE_POSN               0x0
#define _TIMER_CONFIG_POSTSCALE_SIZE               0x4
#define _TIMER_CONFIG_POSTSCALE_MASK               0x00000000f
#define _TIMER_CONFIG_RESERVED0_POSN               0x4
#define _TIMER_CONFIG_RESERVED0_SIZE               0x4
#define _TIMER_CONFIG_RESERVED0_MASK               0x0000000f0
#define _TIMER_CONFIG_PRESCALE_POSN                0x8
#define _TIMER_CONFIG_PRESCALE_SIZE                0x8
#define _TIMER_CONFIG_PRESCALE_MASK                0x00000ff00
#define _TIMER_CONFIG_ZERO_CMP_POSN                0x10
#define _TIMER_CONFIG_ZERO_CMP_SIZE                0x1
#define _TIMER_CONFIG_ZERO_CMP_MASK                0x000010000
#define _TIMER_CONFIG_COUNT_UP_POSN                0x11
#define _TIMER_CONFIG_COUNT_UP_SIZE                0x1
#define _TIMER_CONFIG_COUNT_UP_MASK                0x000020000
#define _TIMER_CONFIG_EN_ONESHOT_POSN              0x12
#define _TIMER_CONFIG_EN_ONESHOT_SIZE              0x1
#define _TIMER_CONFIG_EN_ONESHOT_MASK              0x000040000
#define _TIMER_CONFIG_EN_ALWAYS_POSN               0x13
#define _TIMER_CONFIG_EN_ALWAYS_SIZE               0x1
#define _TIMER_CONFIG_EN_ALWAYS_MASK               0x000080000
#define _TIMER_CONFIG_CLOCK_SOURCE_POSN            0x14
#define _TIMER_CONFIG_CLOCK_SOURCE_SIZE            0x1
#define _TIMER_CONFIG_CLOCK_SOURCE_MASK            0x000100000
#define _TIMER_CONFIG_STICKY_POSN                  0x15
#define _TIMER_CONFIG_STICKY_SIZE                  0x1
#define _TIMER_CONFIG_STICKY_MASK                  0x000200000
#define _TIMER_CONFIG_COMPARE_IE_POSN              0x16
#define _TIMER_CONFIG_COMPARE_IE_SIZE              0x1
#define _TIMER_CONFIG_COMPARE_IE_MASK              0x000400000
#define _TIMER_CONFIG_OVERFLOW_IE_POSN             0x17
#define _TIMER_CONFIG_OVERFLOW_IE_SIZE             0x1
#define _TIMER_CONFIG_OVERFLOW_IE_MASK             0x000800000
#define _TIMER_CONFIG_COMPARE_IF_POSN              0x18
#define _TIMER_CONFIG_COMPARE_IF_SIZE              0x1
#define _TIMER_CONFIG_COMPARE_IF_MASK              0x001000000
#define _TIMER_CONFIG_OVERFLOW_IF_POSN             0x19
#define _TIMER_CONFIG_OVERFLOW_IF_SIZE             0x1
#define _TIMER_CONFIG_OVERFLOW_IF_MASK             0x002000000
#define _TIMER_CONFIG_COMPARE_IP_POSN              0x1a
#define _TIMER_CONFIG_COMPARE_IP_SIZE              0x1
#define _TIMER_CONFIG_COMPARE_IP_MASK              0x004000000
#define _TIMER_CONFIG_OVERFLOW_IP_POSN             0x1b
#define _TIMER_CONFIG_OVERFLOW_IP_SIZE             0x1
#define _TIMER_CONFIG_OVERFLOW_IP_MASK             0x008000000
#define _TIMER_CONFIG_RESERVED1_POSN               0x1c
#define _TIMER_CONFIG_RESERVED1_SIZE               0x6
#define _TIMER_CONFIG_RESERVED1_MASK               0x3f0000000


typedef union {
  struct {
    unsigned long long value                     : 47;
    unsigned long reserved                       : 18;
  };
} timer_counter_t;

#define _TIMER_COUNTER_VALUE_POSN                  0x0
#define _TIMER_COUNTER_VALUE_SIZE                  0x2f
#define _TIMER_COUNTER_VALUE_MASK                  0x000007fffffffffff
#define _TIMER_COUNTER_RESERVED_POSN               0x2f
#define _TIMER_COUNTER_RESERVED_SIZE               0x12
#define _TIMER_COUNTER_RESERVED_MASK               0x1ffff800000000000


typedef union {
  struct {
    unsigned long value                          : 32;
  };
} timer_scounter_t;

#define _TIMER_SCOUNTER_VALUE_POSN                 0x0
#define _TIMER_SCOUNTER_VALUE_SIZE                 0x20
#define _TIMER_SCOUNTER_VALUE_MASK                 0xffffffff



//uart_registers:

typedef union {
  struct {
    unsigned long value                          : 8;
    unsigned long reserved                       : 24;
  };
} uart_data_t;

#define _UART_DATA_VALUE_POSN                      0x0
#define _UART_DATA_VALUE_SIZE                      0x8
#define _UART_DATA_VALUE_MASK                      0x000000ff
#define _UART_DATA_RESERVED_POSN                   0x8
#define _UART_DATA_RESERVED_SIZE                   0x18
#define _UART_DATA_RESERVED_MASK                   0xffffff00


typedef union {
  struct {
    unsigned long baudrate                       : 16;
    unsigned long tx_en                          : 1;
    unsigned long rx_en                          : 1;
    unsigned long parity                         : 1;
    unsigned long nb_stop_bits                   : 1;
    unsigned long reserved                       : 12;
  };
} uart_config_t;

#define _UART_CONFIG_BAUDRATE_POSN                 0x0
#define _UART_CONFIG_BAUDRATE_SIZE                 0x10
#define _UART_CONFIG_BAUDRATE_MASK                 0x0000ffff
#define _UART_CONFIG_TX_EN_POSN                    0x10
#define _UART_CONFIG_TX_EN_SIZE                    0x1
#define _UART_CONFIG_TX_EN_MASK                    0x00010000
#define _UART_CONFIG_RX_EN_POSN                    0x11
#define _UART_CONFIG_RX_EN_SIZE                    0x1
#define _UART_CONFIG_RX_EN_MASK                    0x00020000
#define _UART_CONFIG_PARITY_POSN                   0x12
#define _UART_CONFIG_PARITY_SIZE                   0x1
#define _UART_CONFIG_PARITY_MASK                   0x00040000
#define _UART_CONFIG_NB_STOP_BITS_POSN             0x13
#define _UART_CONFIG_NB_STOP_BITS_SIZE             0x1
#define _UART_CONFIG_NB_STOP_BITS_MASK             0x00080000
#define _UART_CONFIG_RESERVED_POSN                 0x14
#define _UART_CONFIG_RESERVED_SIZE                 0xc
#define _UART_CONFIG_RESERVED_MASK                 0xfff00000


typedef union {
  struct {
    unsigned long tx_full                        : 1;
    unsigned long rx_empty                       : 1;
    unsigned long reserved                       : 30;
  };
} uart_status_t;

#define _UART_STATUS_TX_FULL_POSN                  0x0
#define _UART_STATUS_TX_FULL_SIZE                  0x1
#define _UART_STATUS_TX_FULL_MASK                  0x00000001
#define _UART_STATUS_RX_EMPTY_POSN                 0x1
#define _UART_STATUS_RX_EMPTY_SIZE                 0x1
#define _UART_STATUS_RX_EMPTY_MASK                 0x00000002
#define _UART_STATUS_RESERVED_POSN                 0x2
#define _UART_STATUS_RESERVED_SIZE                 0x1e
#define _UART_STATUS_RESERVED_MASK                 0xfffffffc



//debug_registers:

typedef union {
  struct {
    unsigned long byte0                          : 8;
    unsigned long byte1                          : 8;
    unsigned long byte2                          : 8;
    unsigned long byte3                          : 8;
  };
} debug_reg32_t;

#define _DEBUG_REG32_BYTE0_POSN                    0x0
#define _DEBUG_REG32_BYTE0_SIZE                    0x8
#define _DEBUG_REG32_BYTE0_MASK                    0x000000ff
#define _DEBUG_REG32_BYTE1_POSN                    0x8
#define _DEBUG_REG32_BYTE1_SIZE                    0x8
#define _DEBUG_REG32_BYTE1_MASK                    0x0000ff00
#define _DEBUG_REG32_BYTE2_POSN                    0x10
#define _DEBUG_REG32_BYTE2_SIZE                    0x8
#define _DEBUG_REG32_BYTE2_MASK                    0x00ff0000
#define _DEBUG_REG32_BYTE3_POSN                    0x18
#define _DEBUG_REG32_BYTE3_SIZE                    0x8
#define _DEBUG_REG32_BYTE3_MASK                    0xff000000



#endif // _AUTOGENERATED_LIB_H_
