---
rtl_path: "rtl"

top_level_file: "picorv32_soc_top.v"
top_level_module: "picorv32_soc_top"

clock_signal: "clk"
reset_signal: "resetn"

file_copy_enable: No
file_copy_source: "/dev/null"
file_copy_dest: "/dev/null"

use_parameters: Yes
start_delimiter: "module picorv32_soc_top #("
stop_delimiter: ") ("

xc7a100t-csg324-1:
   fmax_synthesis:
      lower_bound: 10
      upper_bound: 100
   custom_freq_synthesis:
      lower_bound: 100
      upper_bound: 500
      step: 10
...
