
###########################################
# Parameter Domain - BranchPred           #
###########################################

start_delimiter: "  // <Pipeline>"
stop_delimiter: "  // </Pipeline>"