# 
# Synthesis run script generated by Vivado
# 

namespace eval rt {
    variable rc
}
set rt::rc [catch {
  uplevel #0 {
    set ::env(BUILTIN_SYNTH) true
    source $::env(HRT_TCL_PATH)/rtSynthPrep.tcl
    rt::HARTNDb_resetJobStats
    rt::HARTNDb_resetSystemStats
    rt::HARTNDb_startSystemStats
    rt::HARTNDb_startJobStats
    set rt::cmdEcho 0
    rt::set_parameter writeXmsg true
    rt::set_parameter enableParallelHelperSpawn true
    set ::env(RT_TMP) "./.Xil/Vivado-1074451-naouna.ims.bordeaux/realtime/tmp"
    if { [ info exists ::env(RT_TMP) ] } {
      file delete -force $::env(RT_TMP)
      file mkdir $::env(RT_TMP)
    }

    rt::delete_design

    rt::set_parameter datapathDensePacking false
    set rt::partid xc7a100tcsg324-1
    source $::env(HRT_TCL_PATH)/rtSynthParallelPrep.tcl
     file delete -force synth_hints.os

    set rt::multiChipSynthesisFlow false
    source $::env(SYNTH_COMMON)/common.tcl
    set rt::defaultWorkLibName xil_defaultlib
    rt::set_parameter defaultVhdlWorkLib xil_defaultlib

    rt::set_parameter loadVhdl2008Libs false
    rt::set_parameter loadVhdl2019Libs false
    rt::set_parameter deferParseUntilElab true
    rt::set_parameter sortHdlCommandLine true
    set rt::useElabCache false
    if {$rt::useElabCache == false} {
      rt::read_verilog -sv -include {
    /net/users/oelmouden/internship/cva6/work/fmax_synthesis/vivado/xc7a100t-csg324-1/CVA6/base/rtl/cache_subsystem/hpdcache/rtl/include
    /net/users/oelmouden/internship/cva6/work/fmax_synthesis/vivado/xc7a100t-csg324-1/CVA6/base/rtl/cache_subsystem/hpdcache/rtl/src/utils/ecc
    /net/users/oelmouden/internship/cva6/work/fmax_synthesis/vivado/xc7a100t-csg324-1/CVA6/base/rtl/cvfpu/src/common_cells/include
    /net/users/oelmouden/internship/cva6/work/fmax_synthesis/vivado/xc7a100t-csg324-1/CVA6/base/rtl/cvfpu/src/common_cells/include/common_cells
    /net/users/oelmouden/internship/cva6/work/fmax_synthesis/vivado/xc7a100t-csg324-1/CVA6/base/rtl/include
  } -define VIVADO {
      /net/users/oelmouden/internship/cva6/work/fmax_synthesis/vivado/xc7a100t-csg324-1/CVA6/base/rtl/cvfpu/src/fpnew_pkg.sv
      /net/users/oelmouden/internship/cva6/work/fmax_synthesis/vivado/xc7a100t-csg324-1/CVA6/base/rtl/include/config_pkg.sv
      /net/users/oelmouden/internship/cva6/work/fmax_synthesis/vivado/xc7a100t-csg324-1/CVA6/base/rtl/include/cv64a6_imafdc_sv39_config_pkg.sv
      /net/users/oelmouden/internship/cva6/work/fmax_synthesis/vivado/xc7a100t-csg324-1/CVA6/base/rtl/include/riscv_pkg.sv
      /net/users/oelmouden/internship/cva6/work/fmax_synthesis/vivado/xc7a100t-csg324-1/CVA6/base/rtl/axi_pkg.sv
      /net/users/oelmouden/internship/cva6/work/fmax_synthesis/vivado/xc7a100t-csg324-1/CVA6/base/rtl/include/ariane_pkg.sv
      /net/users/oelmouden/internship/cva6/work/fmax_synthesis/vivado/xc7a100t-csg324-1/CVA6/base/rtl/include/build_config_pkg.sv
      /net/users/oelmouden/internship/cva6/work/fmax_synthesis/vivado/xc7a100t-csg324-1/CVA6/base/rtl/include/wt_cache_pkg.sv
      /net/users/oelmouden/internship/cva6/work/fmax_synthesis/vivado/xc7a100t-csg324-1/CVA6/base/rtl/include/std_cache_pkg.sv
      /net/users/oelmouden/internship/cva6/work/fmax_synthesis/vivado/xc7a100t-csg324-1/CVA6/base/rtl/include/instr_tracer_pkg.sv
      /net/users/oelmouden/internship/cva6/work/fmax_synthesis/vivado/xc7a100t-csg324-1/CVA6/base/rtl/include/aes_pkg.sv
      /net/users/oelmouden/internship/cva6/work/fmax_synthesis/vivado/xc7a100t-csg324-1/CVA6/base/rtl/include/dummy_l15_pkg.sv
      /net/users/oelmouden/internship/cva6/work/fmax_synthesis/vivado/xc7a100t-csg324-1/CVA6/base/rtl/include/triggers_pkg.sv
      /net/users/oelmouden/internship/cva6/work/fmax_synthesis/vivado/xc7a100t-csg324-1/CVA6/base/rtl/pmp/tb/tb_pkg.sv
      /net/users/oelmouden/internship/cva6/work/fmax_synthesis/vivado/xc7a100t-csg324-1/CVA6/base/rtl/cvxif_example/include/cvxif_instr_pkg.sv
      /net/users/oelmouden/internship/cva6/work/fmax_synthesis/vivado/xc7a100t-csg324-1/CVA6/base/rtl/cvfpu/src/common_cells/src/cb_filter_pkg.sv
      /net/users/oelmouden/internship/cva6/work/fmax_synthesis/vivado/xc7a100t-csg324-1/CVA6/base/rtl/cvfpu/src/common_cells/src/cf_math_pkg.sv
      /net/users/oelmouden/internship/cva6/work/fmax_synthesis/vivado/xc7a100t-csg324-1/CVA6/base/rtl/cvfpu/src/common_cells/src/ecc_pkg.sv
      /net/users/oelmouden/internship/cva6/work/fmax_synthesis/vivado/xc7a100t-csg324-1/CVA6/base/rtl/cache_subsystem/hpdcache/rtl/src/hpdcache_pkg.sv
      /net/users/oelmouden/internship/cva6/work/fmax_synthesis/vivado/xc7a100t-csg324-1/CVA6/base/rtl/cache_subsystem/hpdcache/rtl/src/hwpf_stride/hwpf_stride_pkg.sv
      /net/users/oelmouden/internship/cva6/work/fmax_synthesis/vivado/xc7a100t-csg324-1/CVA6/base/rtl/cache_subsystem/hpdcache/rtl/src/target/cva6/cva6_op_hpdcache_params_pkg.sv
      /net/users/oelmouden/internship/cva6/work/fmax_synthesis/vivado/xc7a100t-csg324-1/CVA6/base/rtl/cache_subsystem/hpdcache/rtl/src/utils/ecc/prim_secded_pkg.sv
      /net/users/oelmouden/internship/cva6/work/fmax_synthesis/vivado/xc7a100t-csg324-1/CVA6/base/rtl/_vivado_ordered_rtl_only.sv
    }
      rt::filesetChecksum
    }
    rt::set_parameter usePostFindUniquification false
    set rt::top cva6_soc_wrapper
    rt::set_parameter enableIncremental true
    rt::set_parameter markDebugPreservationLevel "enable"
    set rt::reportTiming false
    rt::set_parameter elaborateOnly true
    rt::set_parameter elaborateRtl true
    rt::set_parameter eliminateRedundantBitOperator false
    rt::set_parameter dataflowBusHighlighting false
    rt::set_parameter generateDataflowBusNetlist false
    rt::set_parameter dataFlowViewInElab false
    rt::set_parameter busViewFixBrokenConnections false
    rt::set_parameter elaborateRtlOnlyFlow false
    rt::set_parameter writeBlackboxInterface true
    rt::set_parameter merge_flipflops true
    rt::set_parameter srlDepthThreshold 3
    rt::set_parameter rstSrlDepthThreshold 4
# MODE: 
    rt::set_parameter webTalkPath {}
    rt::set_parameter synthDebugLog false
    rt::set_parameter printModuleName false
    rt::set_parameter enableSplitFlowPath "./.Xil/Vivado-1074451-naouna.ims.bordeaux/"
    set ok_to_delete_rt_tmp true 
    if { [rt::get_parameter parallelDebug] } { 
       set ok_to_delete_rt_tmp false 
    } 
    if {$rt::useElabCache == false} {
        set oldMIITMVal [rt::get_parameter maxInputIncreaseToMerge]; rt::set_parameter maxInputIncreaseToMerge 1000
        set oldCDPCRL [rt::get_parameter createDfgPartConstrRecurLimit]; rt::set_parameter createDfgPartConstrRecurLimit 1
        $rt::db readXRFFile
      rt::run_rtlelab -module $rt::top
        rt::set_parameter maxInputIncreaseToMerge $oldMIITMVal
        rt::set_parameter createDfgPartConstrRecurLimit $oldCDPCRL
    }

    set rt::flowresult [ source $::env(SYNTH_COMMON)/flow.tcl ]
    rt::HARTNDb_stopJobStats
    if { $rt::flowresult == 1 } { return -code error }


    if { [ info exists ::env(RT_TMP) ] } {
      if { [info exists ok_to_delete_rt_tmp] && $ok_to_delete_rt_tmp } { 
        file delete -force $::env(RT_TMP)
      }
    }

    source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
  } ; #end uplevel
} rt::result]

if { $rt::rc } {
uplevel #0 { 
   $rt::db resetHdlParse
   set hsKey [rt::get_parameter helper_shm_key] 
   if { $hsKey != "" && [info exists ::env(BUILTIN_SYNTH)] && [rt::get_parameter enableParallelHelperSpawn] } { 
      $rt::db killSynthHelper $hsKey
   } 
   source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
   return -code "error" $rt::result
 }
}
