
###########################################
# Parameter Domain - BranchPred           #
###########################################

start_delimiter: "  // <Shifter>"
stop_delimiter: "  // </Shifter>"