arch_name: picorv32/timing
arch_display_name: picorv32/timing
lib_name: LIB_xc7a100t-csg324-1_picorv32_timing
target: xc7a100t-csg324-1
rtl_path: rtl
script_path: work/fmax_synthesis/vivado/xc7a100t-csg324-1/picorv32/timing/scripts
report_path: work/fmax_synthesis/vivado/xc7a100t-csg324-1/picorv32/timing/report
log_path: work/fmax_synthesis/vivado/xc7a100t-csg324-1/picorv32/timing/log
tmp_path: work/fmax_synthesis/vivado/xc7a100t-csg324-1/picorv32/timing
design_path: null
design_path_whitelist: []
design_path_blacklist: []
source_rtl_path: rtl
arch_path: odatix_userconfig/architectures
clock_signal: clk
reset_signal: resetn
top_level_module: picorv32_soc_top
top_level_file: picorv32_soc_top.v
use_parameters: true
start_delimiter: 'module picorv32_soc_top #('
stop_delimiter: ) (
file_copy_enable: false
file_copy_source: /dev/null
file_copy_dest: /dev/null
script_copy_enable: false
script_copy_source: /dev/null
fmax_lower_bound: '50'
fmax_upper_bound: '500'
range_list: null
target_frequency: 0
param_target_filename: rtl/picorv32_soc_top.v
generate_rtl: false
generate_command: ''
constraint_filename: constraints.xdc
install_path: /net/users/oelmouden/picorv32
param_domains: {}
continue_on_error: false
force_single_thread: false
