
###########################################
# Parameter Domain - BranchPred           #
###########################################

start_delimiter: "  // <BranchPred>"
stop_delimiter: "  // </BranchPred>"