vendor/pulp-platform/fpga-support/rtl/SyncDpRam.sv
vendor/pulp-platform/fpga-support/rtl/AsyncDpRam.sv
vendor/pulp-platform/fpga-support/rtl/AsyncThreePortRam.sv
vendor/pulp-platform/fpga-support/rtl/SyncThreePortRam.sv
vendor/pulp-platform/fpga-support/rtl/SyncDpRam_ind_r_w.sv
core/cvfpu/src/fpnew_pkg.sv
core/cvfpu/src/fpnew_cast_multi.sv
core/cvfpu/src/fpnew_classifier.sv
core/cvfpu/vendor/opene906/E906_RTL_FACTORY/gen_rtl/clk/rtl/gated_clk_cell.v
core/cvfpu/vendor/opene906/E906_RTL_FACTORY/gen_rtl/fdsu/rtl/pa_fdsu_ctrl.v
core/cvfpu/vendor/opene906/E906_RTL_FACTORY/gen_rtl/fdsu/rtl/pa_fdsu_ff1.v
core/cvfpu/vendor/opene906/E906_RTL_FACTORY/gen_rtl/fdsu/rtl/pa_fdsu_pack_single.v
core/cvfpu/vendor/opene906/E906_RTL_FACTORY/gen_rtl/fdsu/rtl/pa_fdsu_prepare.v
core/cvfpu/vendor/opene906/E906_RTL_FACTORY/gen_rtl/fdsu/rtl/pa_fdsu_round_single.v
core/cvfpu/vendor/opene906/E906_RTL_FACTORY/gen_rtl/fdsu/rtl/pa_fdsu_special.v
core/cvfpu/vendor/opene906/E906_RTL_FACTORY/gen_rtl/fdsu/rtl/pa_fdsu_srt_single.v
core/cvfpu/vendor/opene906/E906_RTL_FACTORY/gen_rtl/fdsu/rtl/pa_fdsu_top.v
core/cvfpu/vendor/opene906/E906_RTL_FACTORY/gen_rtl/fpu/rtl/pa_fpu_dp.v
core/cvfpu/vendor/opene906/E906_RTL_FACTORY/gen_rtl/fpu/rtl/pa_fpu_frbus.v
core/cvfpu/vendor/opene906/E906_RTL_FACTORY/gen_rtl/fpu/rtl/pa_fpu_src_type.v
core/cvfpu/vendor/openc910/C910_RTL_FACTORY/gen_rtl/vfdsu/rtl/ct_vfdsu_ctrl.v
core/cvfpu/vendor/openc910/C910_RTL_FACTORY/gen_rtl/vfdsu/rtl/ct_vfdsu_double.v
core/cvfpu/vendor/openc910/C910_RTL_FACTORY/gen_rtl/vfdsu/rtl/ct_vfdsu_ff1.v
core/cvfpu/vendor/openc910/C910_RTL_FACTORY/gen_rtl/vfdsu/rtl/ct_vfdsu_pack.v
core/cvfpu/vendor/openc910/C910_RTL_FACTORY/gen_rtl/vfdsu/rtl/ct_vfdsu_prepare.v
core/cvfpu/vendor/openc910/C910_RTL_FACTORY/gen_rtl/vfdsu/rtl/ct_vfdsu_round.v
core/cvfpu/vendor/openc910/C910_RTL_FACTORY/gen_rtl/vfdsu/rtl/ct_vfdsu_scalar_dp.v
core/cvfpu/vendor/openc910/C910_RTL_FACTORY/gen_rtl/vfdsu/rtl/ct_vfdsu_srt_radix16_bound_table.v
core/cvfpu/vendor/openc910/C910_RTL_FACTORY/gen_rtl/vfdsu/rtl/ct_vfdsu_srt_radix16_with_sqrt.v
core/cvfpu/vendor/openc910/C910_RTL_FACTORY/gen_rtl/vfdsu/rtl/ct_vfdsu_srt.v
core/cvfpu/vendor/openc910/C910_RTL_FACTORY/gen_rtl/vfdsu/rtl/ct_vfdsu_top.v
core/cvfpu/src/fpnew_divsqrt_th_32.sv
core/cvfpu/src/fpnew_divsqrt_th_64_multi.sv
core/cvfpu/src/fpnew_divsqrt_multi.sv
core/cvfpu/src/fpnew_fma_multi.sv
core/cvfpu/src/fpnew_fma.sv
core/cvfpu/src/fpnew_noncomp.sv
core/cvfpu/src/fpnew_opgroup_block.sv
core/cvfpu/src/fpnew_opgroup_fmt_slice.sv
core/cvfpu/src/fpnew_opgroup_multifmt_slice.sv
core/cvfpu/src/fpnew_rounding.sv
core/cvfpu/src/fpnew_top.sv
core/cvfpu/src/fpu_div_sqrt_mvp/hdl/defs_div_sqrt_mvp.sv
core/cvfpu/src/fpu_div_sqrt_mvp/hdl/control_mvp.sv
core/cvfpu/src/fpu_div_sqrt_mvp/hdl/div_sqrt_top_mvp.sv
core/cvfpu/src/fpu_div_sqrt_mvp/hdl/iteration_div_sqrt_mvp.sv
core/cvfpu/src/fpu_div_sqrt_mvp/hdl/norm_div_sqrt_mvp.sv
core/cvfpu/src/fpu_div_sqrt_mvp/hdl/nrbd_nrsc_mvp.sv
core/cvfpu/src/fpu_div_sqrt_mvp/hdl/preprocess_mvp.sv
core/include/config_pkg.sv
core/include/cv32a6_imac_sv32_config_pkg.sv
core/include/riscv_pkg.sv
core/include/ariane_pkg.sv
vendor/pulp-platform/axi/src/axi_pkg.sv
vendor/pulp-platform/axi/src/axi_intf.sv
core/axi2mem.sv
core/include/ariane_axi_pkg.sv
core/include/wt_cache_pkg.sv
core/include/std_cache_pkg.sv
core/include/instr_tracer_pkg.sv
core/include/build_config_pkg.sv
core/include/aes_pkg.sv
core/include/triggers_pkg.sv
core/cvxif_compressed_if_driver.sv
core/cvxif_issue_register_commit_if_driver.sv
core/cvxif_example/include/cvxif_instr_pkg.sv
core/cvxif_fu.sv
core/cvxif_example/cvxif_example_coprocessor.sv
core/cvxif_example/instr_decoder.sv
core/cvxif_example/compressed_instr_decoder.sv
core/cvxif_example/copro_alu.sv
vendor/pulp-platform/common_cells/src/cf_math_pkg.sv
vendor/pulp-platform/common_cells/src/fifo_v3.sv
vendor/pulp-platform/common_cells/src/lfsr.sv
vendor/pulp-platform/common_cells/src/lfsr_8bit.sv
vendor/pulp-platform/common_cells/src/stream_arbiter.sv
vendor/pulp-platform/common_cells/src/stream_arbiter_flushable.sv
vendor/pulp-platform/common_cells/src/stream_mux.sv
vendor/pulp-platform/common_cells/src/stream_demux.sv
vendor/pulp-platform/common_cells/src/lzc.sv
vendor/pulp-platform/common_cells/src/rr_arb_tree.sv
vendor/pulp-platform/common_cells/src/shift_reg.sv
vendor/pulp-platform/common_cells/src/unread.sv
vendor/pulp-platform/common_cells/src/popcount.sv
vendor/pulp-platform/common_cells/src/exp_backoff.sv
vendor/pulp-platform/common_cells/src/counter.sv
vendor/pulp-platform/common_cells/src/delta_counter.sv
core/cva6.sv
core/cva6_rvfi_probes.sv
core/alu.sv
core/alu_wrapper.sv
core/aes.sv
core/fpu_wrap.sv
core/branch_unit.sv
core/compressed_decoder.sv
core/macro_decoder.sv
core/controller.sv
core/zcmt_decoder.sv
core/csr_buffer.sv
core/csr_regfile.sv
core/trigger_module.sv
core/decoder.sv
core/ex_stage.sv
core/instr_realign.sv
core/id_stage.sv
core/issue_read_operands.sv
core/issue_stage.sv
core/load_unit.sv
core/load_store_unit.sv
core/lsu_bypass.sv
core/mult.sv
core/multiplier.sv
core/serdiv.sv
core/perf_counters.sv
core/ariane_regfile_ff.sv
core/ariane_regfile_fpga.sv
core/scoreboard.sv
core/raw_checker.sv
core/store_buffer.sv
core/amo_buffer.sv
core/store_unit.sv
core/commit_stage.sv
core/axi_shim.sv
core/cva6_accel_first_pass_decoder_stub.sv
core/acc_dispatcher.sv
core/cva6_fifo_v3.sv
core/frontend/btb.sv
core/frontend/bht.sv
core/frontend/bht2lvl.sv
core/frontend/ras.sv
core/frontend/instr_scan.sv
core/frontend/instr_queue.sv
core/frontend/frontend.sv
core/cache_subsystem/wt_dcache_ctrl.sv
core/cache_subsystem/wt_dcache_mem.sv
core/cache_subsystem/wt_dcache_missunit.sv
core/cache_subsystem/wt_dcache_wbuffer.sv
core/cache_subsystem/wt_dcache.sv
core/cache_subsystem/cva6_icache.sv
core/cache_subsystem/wt_cache_subsystem.sv
core/cache_subsystem/wt_axi_adapter.sv
core/cache_subsystem/tag_cmp.sv
core/cache_subsystem/axi_adapter.sv
core/cache_subsystem/miss_handler.sv
core/cache_subsystem/cache_ctrl.sv
core/cache_subsystem/cva6_icache_axi_wrapper.sv
core/cache_subsystem/std_cache_subsystem.sv
core/cache_subsystem/std_nbdcache.sv
core/cache_subsystem/hpdcache/rtl/src/hpdcache_pkg.sv
core/cache_subsystem/hpdcache/rtl/src/utils/hpdcache_mem_req_read_arbiter.sv
core/cache_subsystem/hpdcache/rtl/src/utils/hpdcache_mem_req_write_arbiter.sv
core/cache_subsystem/hpdcache/rtl/src/common/hpdcache_demux.sv
core/cache_subsystem/hpdcache/rtl/src/common/hpdcache_lfsr.sv
core/cache_subsystem/hpdcache/rtl/src/common/hpdcache_sync_buffer.sv
core/cache_subsystem/hpdcache/rtl/src/common/hpdcache_fifo_reg.sv
core/cache_subsystem/hpdcache/rtl/src/common/hpdcache_fifo_reg_initialized.sv
core/cache_subsystem/hpdcache/rtl/src/common/hpdcache_fxarb.sv
core/cache_subsystem/hpdcache/rtl/src/common/hpdcache_rrarb.sv
core/cache_subsystem/hpdcache/rtl/src/common/hpdcache_mux.sv
core/cache_subsystem/hpdcache/rtl/src/common/hpdcache_decoder.sv
core/cache_subsystem/hpdcache/rtl/src/common/hpdcache_1hot_to_binary.sv
core/cache_subsystem/hpdcache/rtl/src/common/hpdcache_prio_1hot_encoder.sv
core/cache_subsystem/hpdcache/rtl/src/common/hpdcache_prio_bin_encoder.sv
core/cache_subsystem/hpdcache/rtl/src/common/hpdcache_sram.sv
core/cache_subsystem/hpdcache/rtl/src/common/hpdcache_sram_wbyteenable.sv
core/cache_subsystem/hpdcache/rtl/src/common/hpdcache_sram_wmask.sv
core/cache_subsystem/hpdcache/rtl/src/common/hpdcache_regbank_wbyteenable_1rw.sv
core/cache_subsystem/hpdcache/rtl/src/common/hpdcache_regbank_wmask_1rw.sv
core/cache_subsystem/hpdcache/rtl/src/common/hpdcache_data_downsize.sv
core/cache_subsystem/hpdcache/rtl/src/common/hpdcache_data_upsize.sv
core/cache_subsystem/hpdcache/rtl/src/common/hpdcache_data_resize.sv
core/cache_subsystem/hpdcache/rtl/src/hwpf_stride/hwpf_stride_pkg.sv
core/cache_subsystem/hpdcache/rtl/src/hwpf_stride/hwpf_stride.sv
core/cache_subsystem/hpdcache/rtl/src/hwpf_stride/hwpf_stride_arb.sv
core/cache_subsystem/hpdcache/rtl/src/hwpf_stride/hwpf_stride_wrapper.sv
core/cache_subsystem/hpdcache/rtl/src/hpdcache.sv
core/cache_subsystem/hpdcache/rtl/src/hpdcache_amo.sv
core/cache_subsystem/hpdcache/rtl/src/hpdcache_cmo.sv
core/cache_subsystem/hpdcache/rtl/src/hpdcache_core_arbiter.sv
core/cache_subsystem/hpdcache/rtl/src/hpdcache_ctrl.sv
core/cache_subsystem/hpdcache/rtl/src/hpdcache_ctrl_pe.sv
core/cache_subsystem/hpdcache/rtl/src/hpdcache_memctrl.sv
core/cache_subsystem/hpdcache/rtl/src/hpdcache_cbuf.sv
core/cache_subsystem/hpdcache/rtl/src/hpdcache_miss_handler.sv
core/cache_subsystem/hpdcache/rtl/src/hpdcache_mshr.sv
core/cache_subsystem/hpdcache/rtl/src/hpdcache_rtab.sv
core/cache_subsystem/hpdcache/rtl/src/hpdcache_uncached.sv
core/cache_subsystem/hpdcache/rtl/src/hpdcache_victim_plru.sv
core/cache_subsystem/hpdcache/rtl/src/hpdcache_victim_random.sv
core/cache_subsystem/hpdcache/rtl/src/hpdcache_victim_sel.sv
core/cache_subsystem/hpdcache/rtl/src/hpdcache_wbuf.sv
core/cache_subsystem/hpdcache/rtl/src/hpdcache_flush.sv
core/cache_subsystem/hpdcache/rtl/src/utils/hpdcache_mem_resp_demux.sv
core/cache_subsystem/hpdcache/rtl/src/utils/hpdcache_mem_to_axi_read.sv
core/cache_subsystem/hpdcache/rtl/src/utils/hpdcache_mem_to_axi_write.sv
core/cache_subsystem/cva6_hpdcache_subsystem.sv
core/cache_subsystem/cva6_hpdcache_subsystem_axi_arbiter.sv
core/cache_subsystem/cva6_hpdcache_if_adapter.sv
core/cache_subsystem/cva6_hpdcache_wrapper.sv
core/cache_subsystem/hpdcache/rtl/src/common/macros/behav/hpdcache_sram_1rw.sv
core/cache_subsystem/hpdcache/rtl/src/common/macros/behav/hpdcache_sram_wbyteenable_1rw.sv
core/cache_subsystem/hpdcache/rtl/src/common/macros/behav/hpdcache_sram_wmask_1rw.sv
core/cache_subsystem/pmp/src/pmp.sv
core/cache_subsystem/pmp/src/pmp_entry.sv
core/cache_subsystem/pmp/src/pmp_data_if.sv
common/local/util/instr_tracer.sv
vendor/pulp-platform/fpga-support/rtl/SyncSpRamBeNx64.sv
common/local/util/tc_sram_fpga_wrapper.sv
common/local/util/tc_sram_wrapper_cache_techno.sv
vendor/pulp-platform/tech_cells_generic/src/rtl/tc_sram.sv
common/local/util/sram.sv
common/local/util/sram_cache.sv
core/cva6_mmu/cva6_mmu.sv
core/cva6_mmu/cva6_ptw.sv
core/cva6_mmu/cva6_tlb.sv
core/cva6_mmu/cva6_shared_tlb.sv
vendor/pulp-platform/axi/src/axi_err_slv.sv
vendor/pulp-platform/common_cells/src/spill_register_flushable.sv
vendor/pulp-platform/common_cells/src/spill_register.sv
vendor/pulp-platform/common_cells/src/onehot_to_bin.sv
vendor/pulp-platform/axi/src/axi_demux.sv
vendor/pulp-platform/common_cells/src/id_queue.sv
vendor/pulp-platform/axi/src/axi_dw_downsizer.sv
vendor/pulp-platform/axi/src/axi_dw_upsizer.sv
vendor/pulp-platform/axi/src/axi_dw_converter.sv
vendor/pulp-platform/common_cells/src/deprecated/fifo_v2.sv
vendor/pulp-platform/common_cells/src/stream_register.sv
vendor/pulp-platform/axi/src/axi_atop_filter.sv
vendor/pulp-platform/axi/src/axi_burst_splitter.sv
vendor/pulp-platform/axi/src/axi_to_axi_lite.sv
core/ariane.sv
core/cva6_wrapper.sv
