
###########################################
# Parameter Domain - BranchPred           #
###########################################

start_delimiter: "  -- <BitManip>"
stop_delimiter: "  -- </BitManip>"