arch_name: neorv32/neorv32_timing
arch_display_name: neorv32/neorv32_timing
lib_name: LIB_xc7a100t-csg324-1_neorv32_neorv32_timing
target: xc7a100t-csg324-1
rtl_path: rtl
script_path: work/fmax_synthesis/vivado/xc7a100t-csg324-1/neorv32/neorv32_timing/scripts
report_path: work/fmax_synthesis/vivado/xc7a100t-csg324-1/neorv32/neorv32_timing/report
log_path: work/fmax_synthesis/vivado/xc7a100t-csg324-1/neorv32/neorv32_timing/log
tmp_path: work/fmax_synthesis/vivado/xc7a100t-csg324-1/neorv32/neorv32_timing
design_path: null
design_path_whitelist: []
design_path_blacklist: []
source_rtl_path: rtl/core
arch_path: odatix_userconfig/architectures
clock_signal: clk_i
reset_signal: rstn_i
top_level_module: neorv32_soc_top
top_level_file: neorv32_soc_top.vhd
use_parameters: true
start_delimiter: generic (
stop_delimiter: );
file_copy_enable: false
file_copy_source: /dev/null
file_copy_dest: /dev/null
script_copy_enable: false
script_copy_source: /dev/null
fmax_lower_bound: '50'
fmax_upper_bound: '300'
range_list: null
target_frequency: 0
param_target_filename: rtl/neorv32_soc_top.vhd
generate_rtl: false
generate_command: ''
constraint_filename: constraints.xdc
install_path: /net/users/oelmouden/neorv32
param_domains: {}
continue_on_error: false
force_single_thread: false
