
###########################################
# Parameter Domain - BranchPred           #
###########################################

start_delimiter: "  // <Scoreboard>"
stop_delimiter: "  // </Scoreboard>"