
###########################################
# Parameter Domain - BranchPred           #
###########################################

start_delimiter: "  // <Frontend>"
stop_delimiter: "  // </Frontend>"