
###########################################
# Parameter Domain - BranchPred           #
###########################################

start_delimiter: "  // <LoadBuff>"
stop_delimiter: "  // </LoadBuff>"